// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushUserReq struct {
	SenderId             int64    `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId           int64    `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty" form:"receiver_id" validate:"required"`
	SendSeq              int32    `protobuf:"varint,3,opt,name=send_seq,json=sendSeq,proto3" json:"send_seq,omitempty" form:"send_seq" validate:"required"`
	MsgType              int32    `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty" form:"msg_type" validate:"required"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty" form:"content" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushUserReq) Reset()         { *m = PushUserReq{} }
func (m *PushUserReq) String() string { return proto.CompactTextString(m) }
func (*PushUserReq) ProtoMessage()    {}
func (*PushUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *PushUserReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushUserReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushUserReq.Merge(m, src)
}
func (m *PushUserReq) XXX_Size() int {
	return m.Size()
}
func (m *PushUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushUserReq proto.InternalMessageInfo

type PushUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushUserResp) Reset()         { *m = PushUserResp{} }
func (m *PushUserResp) String() string { return proto.CompactTextString(m) }
func (*PushUserResp) ProtoMessage()    {}
func (*PushUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *PushUserResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushUserResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushUserResp.Merge(m, src)
}
func (m *PushUserResp) XXX_Size() int {
	return m.Size()
}
func (m *PushUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_PushUserResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PushUserReq)(nil), "push.interface.v1.PushUserReq")
	proto.RegisterType((*PushUserResp)(nil), "push.interface.v1.PushUserResp")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0xc6, 0x77, 0xda, 0xae, 0xbb, 0x9d, 0x5d, 0x04, 0xe7, 0x20, 0xb1, 0x2b, 0x69, 0x88, 0xb0,
	0x16, 0xc1, 0x09, 0x2a, 0x78, 0xf0, 0x24, 0x01, 0x0f, 0x8b, 0x97, 0xa5, 0xfe, 0x39, 0x78, 0x29,
	0xd3, 0xe4, 0xed, 0x74, 0x60, 0x33, 0x33, 0x99, 0x99, 0x14, 0x7a, 0xf5, 0x2b, 0x08, 0xe2, 0xd7,
	0xf1, 0xd6, 0xa3, 0xe0, 0xbd, 0x68, 0xf5, 0x13, 0xf4, 0x13, 0x48, 0x92, 0x86, 0x16, 0x35, 0xb7,
	0xbc, 0xcf, 0xef, 0x7d, 0x7f, 0x87, 0x3c, 0x83, 0xfb, 0x4c, 0x0b, 0xaa, 0x8d, 0x72, 0x8a, 0xdc,
	0xd1, 0x85, 0x9d, 0x53, 0x21, 0x1d, 0x98, 0x19, 0x4b, 0x80, 0x2e, 0x9e, 0x0c, 0x1e, 0x73, 0xe1,
	0xe6, 0xc5, 0x94, 0x26, 0x2a, 0x8b, 0xb8, 0xe2, 0x2a, 0xaa, 0x36, 0xa7, 0xc5, 0xac, 0x9a, 0xaa,
	0xa1, 0xfa, 0xaa, 0x0d, 0x83, 0x0b, 0xae, 0x14, 0xbf, 0x81, 0xfd, 0x16, 0x64, 0xda, 0x2d, 0x77,
	0xf0, 0xfe, 0x0e, 0x32, 0x2d, 0x22, 0x26, 0xa5, 0x72, 0xcc, 0x09, 0x25, 0x6d, 0x4d, 0xc3, 0xaf,
	0x1d, 0x7c, 0x76, 0x5d, 0xd8, 0xf9, 0x3b, 0x0b, 0x66, 0x0c, 0x39, 0xb9, 0xc0, 0x7d, 0x0b, 0x32,
	0x05, 0x33, 0x11, 0xa9, 0x87, 0x02, 0x34, 0xea, 0x8e, 0x4f, 0xeb, 0xe0, 0x2a, 0x25, 0xaf, 0xf1,
	0x99, 0x81, 0x04, 0xc4, 0xa2, 0xc6, 0x9d, 0x12, 0xc7, 0x8f, 0xb6, 0xeb, 0xe1, 0xe5, 0x4c, 0x99,
	0xec, 0x45, 0x78, 0x00, 0xc3, 0x60, 0xc1, 0x6e, 0x44, 0xca, 0x1c, 0x94, 0x71, 0x5e, 0x08, 0x03,
	0x69, 0x38, 0xc6, 0xcd, 0xc6, 0x55, 0x4a, 0x62, 0x5c, 0x89, 0x27, 0x16, 0x72, 0xaf, 0x1b, 0xa0,
	0xd1, 0x71, 0xfc, 0x70, 0xbb, 0x1e, 0x3e, 0xa8, 0x4d, 0x0d, 0xf9, 0xbf, 0xe6, 0xa4, 0xc4, 0x6f,
	0x20, 0x2f, 0x1d, 0x99, 0xe5, 0x13, 0xb7, 0xd4, 0xe0, 0xf5, 0xfe, 0x76, 0x34, 0xa4, 0xc5, 0x91,
	0x59, 0xfe, 0x76, 0xa9, 0x81, 0xbc, 0xc4, 0x27, 0x89, 0x92, 0x0e, 0xa4, 0xf3, 0x8e, 0x03, 0x34,
	0xea, 0xc7, 0x97, 0xdb, 0xf5, 0x30, 0xac, 0x15, 0x3b, 0xd0, 0x62, 0x68, 0xe8, 0x6d, 0x7c, 0xbe,
	0xff, 0x85, 0x56, 0x3f, 0xfd, 0x8c, 0x70, 0xaf, 0x0c, 0xc8, 0x73, 0xdc, 0xbb, 0x16, 0x92, 0x93,
	0xbb, 0xb4, 0xee, 0x80, 0x36, 0x05, 0xd1, 0x57, 0x65, 0x41, 0x83, 0x96, 0x9c, 0xbc, 0xc7, 0xa7,
	0x8d, 0x90, 0xf8, 0xf4, 0x9f, 0xe7, 0x41, 0x0f, 0x0a, 0x6b, 0x73, 0x84, 0xe4, 0xe3, 0xf7, 0xdf,
	0x9f, 0x3a, 0xe7, 0x21, 0x8e, 0xca, 0xfb, 0xa8, 0xb0, 0x60, 0xe2, 0x7b, 0xab, 0x9f, 0xfe, 0xd1,
	0x6a, 0xe3, 0xa3, 0x6f, 0x1b, 0x1f, 0xfd, 0xd8, 0xf8, 0xe8, 0xcb, 0x2f, 0xff, 0xe8, 0x43, 0x97,
	0x69, 0x31, 0xbd, 0x55, 0x9d, 0x3f, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x76, 0xad, 0x32, 0x1c,
	0x98, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PushClient is the client API for Push service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PushClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	//`midware:"auth"`
	PushUser(ctx context.Context, in *PushUserReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type pushClient struct {
	cc *grpc.ClientConn
}

func NewPushClient(cc *grpc.ClientConn) PushClient {
	return &pushClient{cc}
}

func (c *pushClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/push.interface.v1.Push/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) PushUser(ctx context.Context, in *PushUserReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/push.interface.v1.Push/PushUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServer is the server API for Push service.
type PushServer interface {
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	//`midware:"auth"`
	PushUser(context.Context, *PushUserReq) (*empty.Empty, error)
}

// UnimplementedPushServer can be embedded to have forward compatible implementations.
type UnimplementedPushServer struct {
}

func (*UnimplementedPushServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedPushServer) PushUser(ctx context.Context, req *PushUserReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushUser not implemented")
}

func RegisterPushServer(s *grpc.Server, srv PushServer) {
	s.RegisterService(&_Push_serviceDesc, srv)
}

func _Push_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.interface.v1.Push/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_PushUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).PushUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.interface.v1.Push/PushUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).PushUser(ctx, req.(*PushUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Push_serviceDesc = grpc.ServiceDesc{
	ServiceName: "push.interface.v1.Push",
	HandlerType: (*PushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Push_Ping_Handler,
		},
		{
			MethodName: "PushUser",
			Handler:    _Push_PushUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func (m *PushUserReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushUserReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushUserReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintApi(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0x2a
	}
	if m.MsgType != 0 {
		i = encodeVarintApi(dAtA, i, uint64(m.MsgType))
		i--
		dAtA[i] = 0x20
	}
	if m.SendSeq != 0 {
		i = encodeVarintApi(dAtA, i, uint64(m.SendSeq))
		i--
		dAtA[i] = 0x18
	}
	if m.ReceiverId != 0 {
		i = encodeVarintApi(dAtA, i, uint64(m.ReceiverId))
		i--
		dAtA[i] = 0x10
	}
	if m.SenderId != 0 {
		i = encodeVarintApi(dAtA, i, uint64(m.SenderId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PushUserResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushUserResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushUserResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func encodeVarintApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PushUserReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SenderId != 0 {
		n += 1 + sovApi(uint64(m.SenderId))
	}
	if m.ReceiverId != 0 {
		n += 1 + sovApi(uint64(m.ReceiverId))
	}
	if m.SendSeq != 0 {
		n += 1 + sovApi(uint64(m.SendSeq))
	}
	if m.MsgType != 0 {
		n += 1 + sovApi(uint64(m.MsgType))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PushUserResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PushUserReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushUserReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushUserReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderId", wireType)
			}
			m.SenderId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverId", wireType)
			}
			m.ReceiverId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendSeq", wireType)
			}
			m.SendSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendSeq |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgType", wireType)
			}
			m.MsgType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PushUserResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushUserResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushUserResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApi = fmt.Errorf("proto: unexpected end of group")
)
