[ServiceConfig]
    ErrorBuffer = 100
[PoolConfig]
    [PoolConfig.ChannelPoolConfig]
        ErrorBuffer =  10
        SleepOnErrorInterval =  1000
        MaxChannelCount =  50
        MaxAckChannelCount = 50
        AckNoWait = false
        GlobalQosCount  = 5
    [PoolConfig.ConnectionPoolConfig]
        URI =  "amqp://root:root@0.0.0.0:5672/"
        ConnectionName =  "ImConnection"
        ErrorBuffer  =  10
        SleepOnErrorInterval =  5000
        MaxConnectionCount = 10
        Heartbeat = 5
        ConnectionTimeout =  10
[PublisherConfig]
		SleepOnIdleInterval = 1000
		SleepOnQueueFullInterval = 1000
		SleepOnErrorInterval = 1000
		LetterBuffer = 1000
		MaxOverBuffer = 1000
		NotificationBuffer = 1000
[EncryptionConfig]
		Enabled = false
[CompressionConfig]
		Enabled = false
