// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"github.com/bilibili/kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// GroupErrCode ecode
var (
	GroupToAddNotExist = ecode.New(120001)
	UserAlreadyInGroup = ecode.New(120002)
)
