// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"github.com/bilibili/kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// AccountErrCode ecode
var (
	AccountNotExist      = ecode.New(10000)
	AccountEmailRepeated = ecode.New(10001)
)
