// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathAccountPing = "/account.service.v1.Account/Ping"
var PathAccountRegister = "/account/register"
var PathAccountGetAuthInfo = "/account/auth"
var PathAccountGetBasicInfo = "/account/basicInfo"

// AccountBMServer is the server API for Account service.
type AccountBMServer interface {
	Ping(ctx context.Context, req *google_protobuf1.Empty) (resp *google_protobuf1.Empty, err error)

	Register(ctx context.Context, req *RegisterReq) (resp *RegisterResp, err error)

	GetAuthInfo(ctx context.Context, req *AuthReq) (resp *AuthResp, err error)

	GetBasicInfo(ctx context.Context, req *BasicInfoReq) (resp *BasicInfo, err error)
}

var AccountSvc AccountBMServer

func accountPing(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := AccountSvc.Ping(c, p)
	c.JSON(resp, err)
}

func accountRegister(c *bm.Context) {
	p := new(RegisterReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := AccountSvc.Register(c, p)
	c.JSON(resp, err)
}

func accountGetAuthInfo(c *bm.Context) {
	p := new(AuthReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := AccountSvc.GetAuthInfo(c, p)
	c.JSON(resp, err)
}

func accountGetBasicInfo(c *bm.Context) {
	p := new(BasicInfoReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := AccountSvc.GetBasicInfo(c, p)
	c.JSON(resp, err)
}

// RegisterAccountBMServer Register the blademaster route
func RegisterAccountBMServer(e *bm.Engine, server AccountBMServer) {
	AccountSvc = server
	e.GET("/account.service.v1.Account/Ping", accountPing)
	e.POST("/account/register", accountRegister)
	e.GET("/account/auth", accountGetAuthInfo)
	e.GET("/account/basicInfo", accountGetBasicInfo)
}
