// Code generated by kratos tool genmc. DO NOT EDIT.

/*
  Package dao is a generated mc cache package.
  It is generated from:
  type _mc interface {
		// mc: -key=keyGroup -type=get
		CacheGroup(c context.Context, id int64) (*model.Group, error)
		// mc: -key=keyGroup -expire=d.demoExpire
		AddCacheGroup(c context.Context, id int64, art *model.Group) (err error)
		// mc: -key=keyGroup
		DeleteGroupCache(c context.Context, id int64) (err error)
	}
*/

package dao

import (
	"context"
	"fmt"

	"chat/app/service/group/internal/model"
	"github.com/bilibili/kratos/pkg/cache/memcache"
	"github.com/bilibili/kratos/pkg/log"
)

var _ _mc

// CacheGroup get data from mc
func (d *dao) CacheGroup(c context.Context, id int64) (res *model.Group, err error) {
	key := keyGroup(id)
	res = &model.Group{}
	if err = d.mc.Get(c, key).Scan(res); err != nil {
		res = nil
		if err == memcache.ErrNotFound {
			err = nil
		}
	}
	if err != nil {
		log.Errorv(c, log.KV("CacheGroup", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}

// AddCacheGroup Set data to mc
func (d *dao) AddCacheGroup(c context.Context, id int64, val *model.Group) (err error) {
	if val == nil {
		return
	}
	key := keyGroup(id)
	item := &memcache.Item{Key: key, Object: val, Expiration: d.demoExpire, Flags: memcache.FlagJSON}
	if err = d.mc.Set(c, item); err != nil {
		log.Errorv(c, log.KV("AddCacheGroup", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}

// DeleteGroupCache delete data from mc
func (d *dao) DeleteGroupCache(c context.Context, id int64) (err error) {
	key := keyGroup(id)
	if err = d.mc.Delete(c, key); err != nil {
		if err == memcache.ErrNotFound {
			err = nil
			return
		}
		log.Errorv(c, log.KV("DeleteGroupCache", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}
