[PoolConfig]
    [PoolConfig.ChannelPoolConfig]
        ErrorBuffer =  10
        SleepOnErrorInterval =  1000
        MaxChannelCount =  5
        MaxAckChannelCount = 25
        AckNoWait = false
        GlobalQosCount  = 5
    [PoolConfig.ConnectionPoolConfig]
        URI =  "amqp://root:root@0.0.0.0:5672/"
        ConnectionName =  "ConsumerConnection"
        ErrorBuffer  =  10
        SleepOnErrorInterval =  5000
        MaxConnectionCount = 5
        Heartbeat = 5
        ConnectionTimeout =  10
[ConsumerConfig]
        QueueName = "im"
		ConsumerName = "imCore"
		AutoAck = false
		Exclusive = false
		NoWait = false
		QosCountOverride = 20
		MessageBuffer = 1000
		ErrorBuffer = 100
		SleepOnErrorInterval = 1
		SleepOnIdleInterval = 0
